/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Cat/Cat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Cat.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cat" position={[-0.042, 0.044, 0.016]} rotation={[0, 0, -0.006]}>
          <primitive object={nodes.spine} />
          <primitive object={nodes.spine003} />
          <primitive object={nodes.tailboneroot} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.neutral_bone} />
          <skinnedMesh name="Brazos" geometry={nodes.Brazos.geometry} material={materials['Material.002']} skeleton={nodes.Brazos.skeleton} />
          <skinnedMesh name="Cabeza" geometry={nodes.Cabeza.geometry} material={materials['Material.002']} skeleton={nodes.Cabeza.skeleton} />
          <skinnedMesh name="Colita" geometry={nodes.Colita.geometry} material={nodes.Colita.material} skeleton={nodes.Colita.skeleton} />
          <skinnedMesh name="Nariz" geometry={nodes.Nariz.geometry} material={materials['Material.002']} skeleton={nodes.Nariz.skeleton} />
          <skinnedMesh name="Ojos" geometry={nodes.Ojos.geometry} material={materials['Material.001']} skeleton={nodes.Ojos.skeleton} />
          <skinnedMesh name="Orejas" geometry={nodes.Orejas.geometry} material={materials['Material.002']} skeleton={nodes.Orejas.skeleton} />
          <skinnedMesh name="Patas" geometry={nodes.Patas.geometry} material={materials['Material.002']} skeleton={nodes.Patas.skeleton} />
          <skinnedMesh name="Tronco" geometry={nodes.Tronco.geometry} material={materials['Material.002']} skeleton={nodes.Tronco.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cat.glb')
