/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/villains/Dog.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Dog.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="DogArmature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Dog">
            <skinnedMesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Pelaje} skeleton={nodes.Plane001.skeleton} />
            <skinnedMesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Oreja} skeleton={nodes.Plane001_1.skeleton} />
            <skinnedMesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.Nariz} skeleton={nodes.Plane001_2.skeleton} />
            <skinnedMesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.Ojos} skeleton={nodes.Plane001_3.skeleton} />
            <skinnedMesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials.Panza} skeleton={nodes.Plane001_4.skeleton} />
            <skinnedMesh name="Plane001_5" geometry={nodes.Plane001_5.geometry} material={materials.Cresta1} skeleton={nodes.Plane001_5.skeleton} />
            <skinnedMesh name="Plane001_6" geometry={nodes.Plane001_6.geometry} material={materials.Cresta2} skeleton={nodes.Plane001_6.skeleton} />
            <skinnedMesh name="Plane001_7" geometry={nodes.Plane001_7.geometry} material={materials.Cresta3} skeleton={nodes.Plane001_7.skeleton} />
            <skinnedMesh name="Plane001_8" geometry={nodes.Plane001_8.geometry} material={materials.Cresta4} skeleton={nodes.Plane001_8.skeleton} />
            <skinnedMesh name="Plane001_9" geometry={nodes.Plane001_9.geometry} material={materials.Cresta5} skeleton={nodes.Plane001_9.skeleton} />
            <skinnedMesh name="Plane001_10" geometry={nodes.Plane001_10.geometry} material={materials.Cresta6} skeleton={nodes.Plane001_10.skeleton} />
            <skinnedMesh name="Plane001_11" geometry={nodes.Plane001_11.geometry} material={materials.Cresta7} skeleton={nodes.Plane001_11.skeleton} />
            <skinnedMesh name="Plane001_12" geometry={nodes.Plane001_12.geometry} material={materials.Argolla} skeleton={nodes.Plane001_12.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Dog.glb')
