/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/world/Level2WorldZone1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Level2WorldZone1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrier_group_6.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_2.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_3.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_4.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_5.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_1.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_1001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_2001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_3001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_4001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_5001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_6001.geometry} material={materials.hept32} />
      <mesh geometry={nodes.barrier_group_7.geometry} material={materials.hept32} />
      <mesh geometry={nodes.Trunk_1003.geometry} material={materials.hept32} />
      <mesh geometry={nodes.non_collider_shrubs.geometry} material={materials.hept32} />
      <mesh geometry={nodes.Trunk_3004.geometry} material={materials.hept32} />
      <mesh geometry={nodes.Trunk_3008.geometry} material={materials.hept32} />
      <mesh geometry={nodes.Trunk_3009.geometry} material={materials.hept32} />
      <mesh geometry={nodes.Trunk_3010.geometry} material={materials.hept32} />
      <mesh geometry={nodes.tree.geometry} material={materials.hept32} />
      <mesh geometry={nodes.dynamic_wooden_fence001.geometry} material={materials.Material} />
      <mesh geometry={nodes.dynamic_wooden_fence002.geometry} material={materials.Material} />
      <mesh geometry={nodes.dynamic_wooden_fence003.geometry} material={materials.Material} />
      <mesh geometry={nodes.dynamic_wooden_fence004.geometry} material={materials.Material} />
      <mesh geometry={nodes.dynamic_ball.geometry} material={materials.hept32} />
    </group>
  )
}

useGLTF.preload('/Level2WorldZone1.glb')
