/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/world/Level2/Level2WorldZone2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Level2WorldZone2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.check2_treesnshrubs.geometry} material={materials.hept32} />
    </group>
  )
}

useGLTF.preload('/Level2WorldZone2.glb')
