/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\assets\models\collectables\Button.glb
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useNavigate } from 'react-router-dom'
import { RigidBody } from '@react-three/rapier'
import CustomText3D from '../../../utils/text/CustomText3D'

export function Button_Circle ({ ruta, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/models/collectables/Button.glb')
  const { actions } = useAnimations(animations, group)
  const navigate = useNavigate()

  const handleButtonClick = () => {
    actions.ButtonAction.play()
    setTimeout(() => {
      actions.ButtonAction.stop()
      navigate(ruta, { replace: true })
    }, 1000)
  }
  return (
    <group ref={group} {...props} dispose={null} onClick={handleButtonClick}>
      <group name='Scene'>
        <RigidBody type='fixed'>
          <mesh name='Base' geometry={nodes.Base.geometry} material={materials['455A64']} />
        </RigidBody>
        <group name='Button'>
          <RigidBody type='fixed'>
            <mesh name='Button_Circle-Mesh001' geometry={nodes['Button_Circle-Mesh001'].geometry} material={materials.F44336} />
            <mesh name='Button_Circle-Mesh001_1' geometry={nodes['Button_Circle-Mesh001_1'].geometry} material={materials['455A64']} />
          </RigidBody>
        </group>
      </group>
      <CustomText3D
        text='¡Pulsa el botón!'
        position={[0, 5, 0]}
        size={0.5}
        rotation={[0, Math.PI, 0]}
      />
    </group>
  )
}

useGLTF.preload('/assets/models/collectables/Button.glb')
