/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/world/Level2/Level2Platforms.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Level2Platforms (props) {
  const { nodes, materials } = useGLTF('/assets/models/world/Level2/Level2Platforms.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <mesh geometry={nodes.Platform.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform001.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform002.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform003.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform004.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform005.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform006.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform008.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform009.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform010.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform011.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform012.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform013.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform014.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform015.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform016.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform017.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Platform007.geometry} material={materials.hept32} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/assets/models/world/Level2/Level2Platforms.glb')
