/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\assets\models\world\Level3World.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Level3World(props) {
  const { nodes, materials } = useGLTF('assets/models/world/Level3World.glb')
  return (
    <RigidBody type='fixed' colliders='trimesh'>
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Maze_Walls.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Floor.geometry} material={materials.Floor} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/Level3World.glb')
