/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/world/Level2Door1.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Level3Door (props) {
  const { nodes, materials } = useGLTF('/assets/models/world/Level3Door.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='hull'>
        <mesh geometry={nodes.Circle005.geometry} material={materials.hept32} />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials.Material} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/assets/models/world/Level3Door.glb')